import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es" | "fr" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    assets: "Assets",
    discovery: "Discovery",
    discovery_dashboard: "Discovery Dashboard",
    discovery_profiles: "Discovery Profiles",
    script_repository: "Script Repository",
    orchestration_repository: "Orchestration Repository",
    integrations: "Integrations",
    asset_change_log: "Asset Change & Integrity Log",
    system_security_audit: "System Security Audit Log",
    exclusion_rules: "Exclusion & Controlled Access Rules",
    enterprise_credential_vault: "Enterprise Credential Vault",
    central_asset_repository: "Central Asset Repository",
    unmanaged_asset_queue: "Unmanaged Asset Queue",
    data_normalization: "Data Normalization & Enrichment",
    software_license_inventory: "Software & License Inventory",
    satellite_server: "Satellite Server",
    agent_status_report: "Agent Status Report",
    agent_discovery: "Agent Discovery",
    agentless_discovery: "Agentless Discovery",
    agent_discovery_job: "Agent Discovery Job",
    user_management: "User Management",
    settings: "Settings",
    all_endpoints: "All Endpoints",
    agent_based: "Agent-based",
    agentless: "Agentless",
    network_scan: "Network Scan",
    scheduled_tasks: "Scheduled Tasks",
    alerts: "Alerts & Notifications",
    reports: "Reports",
    system_status: "System Status",
    overview_subtitle: "Endpoint management overview",
    total_endpoints: "Total Endpoints",
    online_endpoints: "Online Endpoints",
    security_alerts: "Security Alerts",
    compliance_score: "Compliance Score",
    from_last_month: "from last month",
    uptime: "uptime",
    critical: "critical",
    from_last_week: "from last week",
    recent_endpoint_activity: "Recent Endpoint Activity",
    view_all: "View All",
    quick_actions: "Quick Actions",
    start_discovery: "Start Discovery Scan",
    add_endpoint: "Add New Endpoint",
    deploy_agent: "Deploy Agent",
    generate_report: "Generate Report",
    discovery_service: "Discovery Service",
    agent_communication: "Agent Communication",
    database: "Database",
    backup_service: "Backup Service",
    online: "Online",
    healthy: "Healthy",
    warning: "Warning",
    running: "Running",
    user_profile: "User Profile",
    preferred_language: "Preferred Language",
    theme_preference: "Theme Preference",
    light_mode: "Light Mode",
    dark_mode: "Dark Mode",
    system_default: "System Default",
    email_notifications: "Email Notifications",
    desktop_notifications: "Desktop Notifications",
    save_changes: "Save Changes",
    logout: "Logout",
    // Scripts and Script Policies
    scripts: "Scripts",
    script_policies: "Script Policies",
    search_scripts: "Search scripts...",
    search_policies: "Search policies...",
    filter_by_os: "Filter by OS",
    all_os: "All OS",
    windows: "Windows",
    linux: "Linux",
    macos: "macOS",
    cross_platform: "Cross-platform",
    filter_by_category: "Filter by Category",
    all_categories: "All Categories",
    applications_databases: "Applications & Databases",
    cloud_virtualization: "Cloud & Virtualization",
    network_connectivity: "Network & Connectivity",
    operating_system: "Operating System",
    security: "Security",
    system_monitoring: "System Monitoring",
    hardware_information: "Hardware Information",
    create_script: "Create New Script",
    create_policy: "Create New Policy",
    edit_script: "Edit Script",
    edit_policy: "Edit Policy",
    script_name: "Script Name",
    script_description: "Description",
    script_category: "Category",
    script_type: "Script Type",
    target_os: "Target OS",
    script_author: "Author",
    script_version: "Version",
    script_content: "Script Content",
    script_parameters: "Parameters",
    script_tags: "Tags",
    powershell: "PowerShell",
    bash: "Bash",
    python: "Python",
    wmi: "WMI",
    policy_name: "Policy Name",
    policy_description: "Policy Description",
    available_scripts: "Available Scripts",
    execution_flow: "Execution Flow",
    is_active: "Active",
    is_favorite: "Favorite",
    execution_count: "Execution Count",
    last_modified: "Last Modified",
    health_checks: "Health Checks", 
    onboarding: "Onboarding",
    activate: "Activate",
    deactivate: "Deactivate",
    delete: "Delete",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading...",
    no_scripts_found: "No scripts found",
    no_policies_found: "No policies found",
    script_created: "Script created successfully",
    script_updated: "Script updated successfully",
    script_deleted: "Script deleted successfully",
    policy_created: "Policy created successfully",
    policy_updated: "Policy updated successfully",
    policy_deleted: "Policy deleted successfully",
    // Policy Status
    draft: "Draft",
    published: "Published",
    maintenance: "Maintenance",
    inactive: "Inactive",
    publish_status: "Publish Status",
    execution_order: "Execution Order",
    add_execution_step: "Add Execution Step",
    step_name: "Step Name",
    select_script: "Select Script",
    search_scripts_placeholder: "Search for scripts...",
    run_condition: "Run Condition",
    always: "Always",
    on_success: "On Success",
    on_failure: "On Failure",
    select_previous_step: "Select Previous Step",
    step_order: "Step Order",
    remove_step: "Remove Step",
  },
  es: {
    dashboard: "Panel de Control",
    assets: "Activos",
    discovery: "Descubrimiento",
    discovery_dashboard: "Panel de Descubrimiento",
    discovery_profiles: "Perfiles de Descubrimiento",
    script_repository: "Repositorio de Scripts",
    orchestration_repository: "Repositorio de Orquestación",
    integrations: "Integraciones",
    asset_change_log: "Registro de Cambios e Integridad de Activos",
    system_security_audit: "Registro de Auditoría de Seguridad del Sistema",
    exclusion_rules: "Reglas de Exclusión y Acceso Controlado",
    enterprise_credential_vault: "Bóveda de Credenciales Empresariales",
    central_asset_repository: "Repositorio Central de Activos",
    unmanaged_asset_queue: "Cola de Activos No Gestionados",
    data_normalization: "Normalización y Enriquecimiento de Datos",
    software_license_inventory: "Inventario de Software y Licencias",
    satellite_server: "Servidor Satélite",
    agent_status_report: "Informe de Estado del Agente",
    agent_discovery: "Descubrimiento de Agente",
    agentless_discovery: "Descubrimiento sin Agente",
    agent_discovery_job: "Trabajo de Descubrimiento de Agente",
    user_management: "Gestión de Usuarios",
    settings: "Configuración",
    all_endpoints: "Todos los Endpoints",
    agent_based: "Basado en Agente",
    agentless: "Sin Agente",
    network_scan: "Escaneo de Red",
    scheduled_tasks: "Tareas Programadas",
    alerts: "Alertas y Notificaciones",
    reports: "Informes",
    system_status: "Estado del Sistema",
    overview_subtitle: "Resumen de gestión de endpoints",
    total_endpoints: "Total de Endpoints",
    online_endpoints: "Endpoints en Línea",
    security_alerts: "Alertas de Seguridad",
    compliance_score: "Puntuación de Cumplimiento",
    from_last_month: "del mes pasado",
    uptime: "tiempo activo",
    critical: "crítico",
    from_last_week: "de la semana pasada",
    recent_endpoint_activity: "Actividad Reciente de Endpoints",
    view_all: "Ver Todo",
    quick_actions: "Acciones Rápidas",
    start_discovery: "Iniciar Escaneo de Descubrimiento",
    add_endpoint: "Agregar Nuevo Endpoint",
    deploy_agent: "Desplegar Agente",
    generate_report: "Generar Informe",
    discovery_service: "Servicio de Descubrimiento",
    agent_communication: "Comunicación de Agente",
    database: "Base de Datos",
    backup_service: "Servicio de Respaldo",
    online: "En Línea",
    healthy: "Saludable",
    warning: "Advertencia",
    running: "Ejecutándose",
    user_profile: "Perfil de Usuario",
    preferred_language: "Idioma Preferido",
    theme_preference: "Preferencia de Tema",
    light_mode: "Modo Claro",
    dark_mode: "Modo Oscuro",
    system_default: "Predeterminado del Sistema",
    email_notifications: "Notificaciones por Correo",
    desktop_notifications: "Notificaciones de Escritorio",
    save_changes: "Guardar Cambios",
    logout: "Cerrar Sesión",
  },
  fr: {
    dashboard: "Tableau de Bord",
    assets: "Actifs",
    discovery: "Découverte",
    discovery_dashboard: "Tableau de Découverte",
    discovery_profiles: "Profils de Découverte",
    script_repository: "Référentiel de Scripts",
    orchestration_repository: "Référentiel d'Orchestration",
    integrations: "Intégrations",
    asset_change_log: "Journal des Modifications et d'Intégrité des Actifs",
    system_security_audit: "Journal d'Audit de Sécurité du Système",
    exclusion_rules: "Règles d'Exclusion et d'Accès Contrôlé",
    enterprise_credential_vault: "Coffre-fort de Références d'Entreprise",
    central_asset_repository: "Référentiel Central des Actifs",
    unmanaged_asset_queue: "File d'Attente des Actifs Non Gérés",
    data_normalization: "Normalisation et Enrichissement des Données",
    software_license_inventory: "Inventaire des Logiciels et Licences",
    satellite_server: "Serveur Satellite",
    agent_status_report: "Rapport d'État de l'Agent",
    agent_discovery: "Découverte d'Agent",
    agentless_discovery: "Découverte sans Agent",
    agent_discovery_job: "Tâche de Découverte d'Agent",
    user_management: "Gestion des Utilisateurs",
    settings: "Paramètres",
    all_endpoints: "Tous les Endpoints",
    agent_based: "Basé sur Agent",
    agentless: "Sans Agent",
    network_scan: "Scan Réseau",
    scheduled_tasks: "Tâches Programmées",
    alerts: "Alertes et Notifications",
    reports: "Rapports",
    system_status: "État du Système",
    overview_subtitle: "Aperçu de la gestion des endpoints",
    total_endpoints: "Total des Endpoints",
    online_endpoints: "Endpoints en Ligne",
    security_alerts: "Alertes de Sécurité",
    compliance_score: "Score de Conformité",
    from_last_month: "du mois dernier",
    uptime: "temps de fonctionnement",
    critical: "critique",
    from_last_week: "de la semaine dernière",
    recent_endpoint_activity: "Activité Récente des Endpoints",
    view_all: "Voir Tout",
    quick_actions: "Actions Rapides",
    start_discovery: "Démarrer Scan de Découverte",
    add_endpoint: "Ajouter Nouvel Endpoint",
    deploy_agent: "Déployer Agent",
    generate_report: "Générer Rapport",
    discovery_service: "Service de Découverte",
    agent_communication: "Communication Agent",
    database: "Base de Données",
    backup_service: "Service de Sauvegarde",
    online: "En Ligne",
    healthy: "Sain",
    warning: "Avertissement",
    running: "En Cours",
    user_profile: "Profil Utilisateur",
    preferred_language: "Langue Préférée",
    theme_preference: "Préférence de Thème",
    light_mode: "Mode Clair",
    dark_mode: "Mode Sombre",
    system_default: "Défaut Système",
    email_notifications: "Notifications Email",
    desktop_notifications: "Notifications Bureau",
    save_changes: "Sauvegarder",
    logout: "Déconnexion",
    // Scripts and Script Policies
    scripts: "Scripts",
    script_policies: "Politiques de Script",
    search_scripts: "Rechercher scripts...",
    search_policies: "Rechercher politiques...",
    filter_by_os: "Filtrer par OS",
    all_os: "Tous les OS",
    windows: "Windows",
    linux: "Linux",
    macos: "macOS",
    cross_platform: "Multi-plateforme",
    filter_by_category: "Filtrer par Catégorie",
    all_categories: "Toutes Catégories",
    applications_databases: "Applications & Bases de Données",
    cloud_virtualization: "Cloud & Virtualisation",
    network_connectivity: "Réseau & Connectivité",
    operating_system: "Système d'Exploitation",
    security: "Sécurité",
    system_monitoring: "Surveillance Système",
    hardware_information: "Informations Matériel",
    create_script: "Créer Nouveau Script",
    create_policy: "Créer Nouvelle Politique",
    edit_script: "Modifier Script",
    edit_policy: "Modifier Politique",
    script_name: "Nom du Script",
    script_description: "Description",
    script_category: "Catégorie",
    script_type: "Type de Script",
    target_os: "OS Cible",
    script_author: "Auteur",
    script_version: "Version",
    script_content: "Contenu du Script",
    script_parameters: "Paramètres",
    script_tags: "Étiquettes",
    powershell: "PowerShell",
    bash: "Bash",
    python: "Python",
    wmi: "WMI",
    policy_name: "Nom de la Politique",
    policy_description: "Description de la Politique",
    available_scripts: "Scripts Disponibles",
    execution_flow: "Flux d'Exécution",
    is_active: "Actif",
    is_favorite: "Favori",
    execution_count: "Nombre d'Exécutions",
    last_modified: "Dernière Modification",
    health_checks: "Vérifications de Santé",
    onboarding: "Intégration",
    activate: "Activer",
    deactivate: "Désactiver",
    delete: "Supprimer",
    edit: "Modifier",
    save: "Sauvegarder",
    cancel: "Annuler",
    close: "Fermer",
    loading: "Chargement...",
    no_scripts_found: "Aucun script trouvé",
    no_policies_found: "Aucune politique trouvée",
    script_created: "Script créé avec succès",
    script_updated: "Script mis à jour avec succès",
    script_deleted: "Script supprimé avec succès",
    policy_created: "Politique créée avec succès",
    policy_updated: "Politique mise à jour avec succès",
    policy_deleted: "Politique supprimée avec succès",
  },
  de: {
    dashboard: "Dashboard",
    assets: "Vermögenswerte",
    discovery: "Erkennung",
    discovery_dashboard: "Erkennungs-Dashboard",
    discovery_profiles: "Erkennungs-Profile",
    script_repository: "Skript-Repository",
    orchestration_repository: "Orchestrierungs-Repository",
    integrations: "Integrationen",
    asset_change_log: "Asset-Änderungs- und Integritätsprotokoll",
    system_security_audit: "System-Sicherheits-Auditprotokoll",
    exclusion_rules: "Ausschluss- und Kontrolliertezugriffsregeln",
    enterprise_credential_vault: "Unternehmens-Anmeldeinformationstresor",
    central_asset_repository: "Zentrales Asset-Repository",
    unmanaged_asset_queue: "Nicht Verwaltete Asset-Warteschlange",
    data_normalization: "Datennormalisierung und -Anreicherung",
    software_license_inventory: "Software- und Lizenzinventar",
    satellite_server: "Satellitenserver",
    agent_status_report: "Agent-Statusbericht",
    agent_discovery: "Agent-Erkennung",
    agentless_discovery: "Agentenlose Erkennung",
    agent_discovery_job: "Agent-Erkennungsauftrag",
    user_management: "Benutzerverwaltung",
    settings: "Einstellungen",
    all_endpoints: "Alle Endpunkte",
    agent_based: "Agent-basiert",
    agentless: "Ohne Agent",
    network_scan: "Netzwerk-Scan",
    scheduled_tasks: "Geplante Aufgaben",
    alerts: "Warnungen & Benachrichtigungen",
    reports: "Berichte",
    system_status: "Systemstatus",
    overview_subtitle: "Endpunkt-Management-Übersicht",
    total_endpoints: "Gesamte Endpunkte",
    online_endpoints: "Online-Endpunkte",
    security_alerts: "Sicherheitswarnungen",
    compliance_score: "Compliance-Score",
    from_last_month: "vom letzten Monat",
    uptime: "Betriebszeit",
    critical: "kritisch",
    from_last_week: "von letzter Woche",
    recent_endpoint_activity: "Kürzliche Endpunkt-Aktivität",
    view_all: "Alle Anzeigen",
    quick_actions: "Schnellaktionen",
    start_discovery: "Erkennungs-Scan Starten",
    add_endpoint: "Neuen Endpunkt Hinzufügen",
    deploy_agent: "Agent Bereitstellen",
    generate_report: "Bericht Generieren",
    discovery_service: "Erkennungsdienst",
    agent_communication: "Agent-Kommunikation",
    database: "Datenbank",
    backup_service: "Backup-Service",
    online: "Online",
    healthy: "Gesund",
    warning: "Warnung",
    running: "Läuft",
    user_profile: "Benutzerprofil",
    preferred_language: "Bevorzugte Sprache",
    theme_preference: "Theme-Präferenz",
    light_mode: "Heller Modus",
    dark_mode: "Dunkler Modus",
    system_default: "System-Standard",
    email_notifications: "E-Mail-Benachrichtigungen",
    desktop_notifications: "Desktop-Benachrichtigungen",
    save_changes: "Änderungen Speichern",
    logout: "Abmelden",
    // Scripts and Script Policies
    scripts: "Skripte",
    script_policies: "Skript-Richtlinien",
    search_scripts: "Skripte suchen...",
    search_policies: "Richtlinien suchen...",
    filter_by_os: "Nach OS filtern",
    all_os: "Alle OS",
    windows: "Windows",
    linux: "Linux",
    macos: "macOS",
    cross_platform: "Plattformübergreifend",
    filter_by_category: "Nach Kategorie filtern",
    all_categories: "Alle Kategorien",
    applications_databases: "Anwendungen & Datenbanken",
    cloud_virtualization: "Cloud & Virtualisierung",
    network_connectivity: "Netzwerk & Konnektivität",
    operating_system: "Betriebssystem",
    security: "Sicherheit",
    system_monitoring: "Systemüberwachung",
    hardware_information: "Hardware-Informationen",
    create_script: "Neues Skript erstellen",
    create_policy: "Neue Richtlinie erstellen",
    edit_script: "Skript bearbeiten",
    edit_policy: "Richtlinie bearbeiten",
    script_name: "Skriptname",
    script_description: "Beschreibung",
    script_category: "Kategorie",
    script_type: "Skripttyp",
    target_os: "Ziel-OS",
    script_author: "Autor",
    script_version: "Version",
    script_content: "Skriptinhalt",
    script_parameters: "Parameter",
    script_tags: "Tags",
    powershell: "PowerShell",
    bash: "Bash",
    python: "Python",
    wmi: "WMI",
    policy_name: "Richtlinienname",
    policy_description: "Richtlinienbeschreibung",
    available_scripts: "Verfügbare Skripte",
    execution_flow: "Ausführungsfluss",
    is_active: "Aktiv",
    is_favorite: "Favorit",
    execution_count: "Ausführungsanzahl",
    last_modified: "Zuletzt Geändert",
    health_checks: "Gesundheitsprüfungen",
    onboarding: "Einarbeitung",
    activate: "Aktivieren",
    deactivate: "Deaktivieren",
    delete: "Löschen",
    edit: "Bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    close: "Schließen",
    loading: "Lädt...",
    no_scripts_found: "Keine Skripte gefunden",
    no_policies_found: "Keine Richtlinien gefunden",
    script_created: "Skript erfolgreich erstellt",
    script_updated: "Skript erfolgreich aktualisiert",
    script_deleted: "Skript erfolgreich gelöscht",
    policy_created: "Richtlinie erfolgreich erstellt",
    policy_updated: "Richtlinie erfolgreich aktualisiert",
    policy_deleted: "Richtlinie erfolgreich gelöscht",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
